# Generated by Django 4.1.7 on 2023-03-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatisthis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
