# Generated by Django 4.1.7 on 2023-03-29 12:24

from django.db import migrations, models
import whatisthis.validators


class Migration(migrations.Migration):

    dependencies = [
        ('whatisthis', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='upload_Image',
            field=models.ImageField(upload_to='images/', validators=[whatisthis.validators.validate_file_size]),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
