# Generated by Django 4.1.6 on 2023-03-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatisthis", "0003_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_file", models.FileField(upload_to="cnn_model.joblib")),
            ],
        ),
    ]
