# Generated by Django 4.1.7 on 2023-03-29 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatisthis', '0004_alter_image_upload_image_delete_profile'),
        ('whatisthis', '0004_mlmodel'),
    ]

    operations = [
    ]
