# Generated by Django 4.1.7 on 2023-03-29 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatisthis', '0005_merge_20230329_2046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MLModel',
        ),
    ]
