# Generated by Django 4.1.7 on 2023-03-31 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatisthis', '0007_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_keywords',
            new_name='task_keyword',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_description',
        ),
    ]
