# Generated by Django 4.1.7 on 2023-04-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatisthis', '0008_rename_task_keywords_task_task_keyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
