# Generated by Django 4.1.7 on 2023-04-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatisthis', '0010_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pin',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
